
import { BlogPosts, CalculatorFormulas, ContactInquiries, FAQs, Products, TeamMembers } from './index';


export const mockCalculatorFormulas: CalculatorFormulas[] = [
  {
    _id: '1',
    formulaName: 'Tile Adhesive Standard Coverage',
    description: 'Calculates the total amount of tile adhesive required for a given area, considering the product\'s coverage rate and an optional wastage percentage.',
    calculationLogic: 'area_sqm * coverageRate_kg_per_sqm * (1 + wastage_percentage / 100)',
    variables: 'area_sqm, coverageRate_kg_per_sqm, wastage_percentage',
    outputUnit: 'kg',
    isActive: true,
    lastUpdated: '2026-01-05',
    _createdDate: new Date('2026-01-05'),
    _updatedDate: new Date('2026-01-06'),
  },
  {
    _id: '2',
    formulaName: 'Tile Grout Calculation',
    description: 'Estimates the quantity of grout needed based on the total area, average joint width, joint depth, and product-specific coverage factor.',
    calculationLogic: 'area_sqm * (jointWidth_mm / 1000) * (jointDepth_mm / 1000) * groutFactor_kg_per_cubic_meter * (1 + wastage_percentage / 100)',
    variables: 'area_sqm, jointWidth_mm, jointDepth_mm, groutFactor_kg_per_cubic_meter, wastage_percentage',
    outputUnit: 'kg',
    isActive: true,
    lastUpdated: '2026-01-05',
    _createdDate: new Date('2026-01-05'),
    _updatedDate: new Date('2026-01-06'),
  },
  {
    _id: '3',
    formulaName: 'Liquid Waterproofing Membrane Coverage',
    description: 'Determines the total liters of liquid waterproofing membrane required for a specified area and number of coats, based on the product\'s per-coat coverage rate.',
    calculationLogic: 'area_sqm * numberOfCoats * coverageRate_liters_per_sqm_per_coat * (1 + wastage_percentage / 100)',
    variables: 'area_sqm, numberOfCoats, coverageRate_liters_per_sqm_per_coat, wastage_percentage',
    outputUnit: 'liters',
    isActive: true,
    lastUpdated: '2026-01-05',
    _createdDate: new Date('2026-01-05'),
    _updatedDate: new Date('2026-01-06'),
  },
  {
    _id: '4',
    formulaName: 'Concrete Repair Mortar Volume',
    description: 'Calculates the total volume of concrete repair mortar needed for a specific repair area and average depth, then converts it to kilograms using product density.',
    calculationLogic: 'area_sqm * (averageDepth_mm / 1000) * density_kg_per_cubic_meter * (1 + wastage_percentage / 100)',
    variables: 'area_sqm, averageDepth_mm, density_kg_per_cubic_meter, wastage_percentage',
    outputUnit: 'kg',
    isActive: true,
    lastUpdated: '2026-01-05',
    _createdDate: new Date('2026-01-05'),
    _updatedDate: new Date('2026-01-06'),
  },
  {
    _id: '5',
    formulaName: 'Self-Leveling Compound Coverage',
    description: 'Estimates the quantity of self-leveling compound required for a given area and desired thickness, considering the product\'s density and an optional wastage.',
    calculationLogic: 'area_sqm * (desiredThickness_mm / 1000) * density_kg_per_cubic_meter * (1 + wastage_percentage / 100)',
    variables: 'area_sqm, desiredThickness_mm, density_kg_per_cubic_meter, wastage_percentage',
    outputUnit: 'kg',
    isActive: true,
    lastUpdated: '2026-01-05',
    _createdDate: new Date('2026-01-05'),
    _updatedDate: new Date('2026-01-06'),
  },
];

export const mockContactInquiries: ContactInquiries[] = [
  {
    _id: '1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '+1-555-123-4567',
    message: 'I am interested in your waterproofing solutions for a commercial project. Could you please send me more information on your product range and pricing?',
    submissionDate: '2026-01-15',
    _createdDate: new Date('2026-01-15'),
    _updatedDate: new Date('2026-01-15'),
  },
  {
    _id: '2',
    name: 'Jane Smith',
    email: 'jane.smith@constructionco.com',
    phone: '+1-555-987-6543',
    message: 'I used your adhesive coverage calculator and have a question about the wastage percentage. Does it account for irregular surfaces? We are planning a large tile installation.',
    submissionDate: '2026-01-15',
    _createdDate: new Date('2026-01-15'),
    _updatedDate: new Date('2026-01-15'),
  },
  {
    _id: '1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '+1-555-123-4567',
    message: 'I am interested in your waterproofing solutions for a commercial project. Could you please send me more information on your product range and pricing?',
    submissionDate: '2026-01-15',
    _createdDate: new Date('2026-01-15'),
    _updatedDate: new Date('2026-01-15'),
  },
];

export const mockFAQs: FAQs[] = [
  {
    _id: '1',
    question: 'How accurate is the material coverage calculator?',
    answer: 'Our material coverage calculator uses product-specific formulas and coverage rates defined by our experts. While it provides highly accurate estimations for planning, actual material usage may vary slightly based on site conditions, application techniques, and waste. We recommend adding a small buffer to your estimates.',
    category: 'Calculator',
    isFeatured: true,
    lastUpdated: '2026-01-12',
    _createdDate: new Date('2026-01-12'),
    _updatedDate: new Date('2026-01-13'),
  },
  {
    _id: '2',
    question: 'What types of construction materials do you offer?',
    answer: 'We offer a comprehensive range of construction materials including waterproofing solutions, tile & stone adhesives and grouts, concrete repair solutions, flooring systems, stamping solutions, decorative surface finishes, texture paint coatings, admixtures, and mortars.',
    category: 'Products',
    isFeatured: true,
    lastUpdated: '2026-01-12',
    _createdDate: new Date('2026-01-12'),
    _updatedDate: new Date('2026-01-13'),
  },
  {
    _id: '3',
    question: 'How do I use the material coverage calculator?',
    answer: 'Simply navigate to the \'Calculator\' section. You can input the length and width of your area or directly enter the total square meters. Then, select the product you intend to use. The calculator will automatically apply the product\'s specific coverage rate and any optional wastage percentage to provide an estimated material quantity.',
    category: 'Calculator',
    isFeatured: true,
    lastUpdated: '2026-01-12',
    _createdDate: new Date('2026-01-12'),
    _updatedDate: new Date('2026-01-13'),
  },
  {
    _id: '4',
    question: 'Can I get technical support for product application?',
    answer: 'Yes, our technical support team is available to assist you with product selection, application guidelines, and troubleshooting. Please contact us via phone or email, or fill out the contact form on our website, and a specialist will get back to you promptly.',
    category: 'Application',
    isFeatured: true,
    lastUpdated: '2026-01-12',
    _createdDate: new Date('2026-01-12'),
    _updatedDate: new Date('2026-01-13'),
  },
  {
    _id: '5',
    question: 'What is the typical delivery time for orders?',
    answer: 'Delivery times vary based on product availability, order size, and your location. Standard deliveries typically take 3-5 business days. For urgent orders or specific delivery inquiries, please contact our sales team directly.',
    category: 'Ordering & Delivery',
    isFeatured: true,
    lastUpdated: '2026-01-12',
    _createdDate: new Date('2026-01-12'),
    _updatedDate: new Date('2026-01-13'),
  },
  {
    _id: '6',
    question: 'Are your products environmentally friendly?',
    answer: 'We are committed to sustainability and offer a range of eco-friendly products designed to minimize environmental impact. Look for specific product certifications and details on our product pages or contact us for more information on our green building solutions.',
    category: 'Products',
    isFeatured: true,
    lastUpdated: '2026-01-12',
    _createdDate: new Date('2026-01-12'),
    _updatedDate: new Date('2026-01-13'),
  },
  {
    _id: '7',
    question: 'How do I find the right product for my project?',
    answer: 'Our website features a detailed product catalog with descriptions, technical data sheets, and application guides. You can browse by category or use the search function. If you need personalized assistance, our experts are happy to provide recommendations based on your project requirements.',
    category: 'Products',
    isFeatured: true,
    lastUpdated: '2026-01-12',
    _createdDate: new Date('2026-01-12'),
    _updatedDate: new Date('2026-01-13'),
  },
  {
    _id: '8',
    question: 'Is the website accessible on mobile devices?',
    answer: 'Yes, our website is fully responsive and optimized for mobile, tablet, and desktop devices. You can access all features, including the material calculator and product catalog, seamlessly from any device. It\'s also a Progressive Web App (PWA) for an enhanced mobile experience.',
    category: 'Website',
    isFeatured: true,
    lastUpdated: '2026-01-12',
    _createdDate: new Date('2026-01-12'),
    _updatedDate: new Date('2026-01-13'),
  },
  {
    _id: '9',
    question: 'What is the difference between tile adhesive and grout?',
    answer: 'Tile adhesive is used to bond tiles to a substrate, providing a strong and durable connection. Grout, on the other hand, is used to fill the spaces between tiles after they have been laid, providing structural integrity, preventing dirt accumulation, and enhancing the aesthetic appeal.',
    category: 'Products',
    isFeatured: true,
    lastUpdated: '2026-01-12',
    _createdDate: new Date('2026-01-12'),
    _updatedDate: new Date('2026-01-13'),
  },
  {
    _id: '10',
    question: 'How can I get a quote for a large project?',
    answer: 'For large-scale projects or bulk orders, please contact our sales department directly through the \'Contact Us\' page. Provide details about your project, including product requirements and quantities, and our team will prepare a customized quote for you.',
    category: 'Ordering & Delivery',
    isFeatured: true,
    lastUpdated: '2026-01-12',
    _createdDate: new Date('2026-01-12'),
    _updatedDate: new Date('2026-01-13'),
  },
];

export const mockProducts: Products[] = [
  {
    _id: '1',
    productName: 'CREED 2K',
    category: 'Waterproofing Solutions',
    description: 'Two-component elastic cementitious waterproofing system for balconies, terraces and wet areas.',
    specifications: 'Elasticity: 40-50%. Tensile Strength: ≥4.5 N/mm². Coverage: 80-100 sq.ft. per 15kg (2 coats). Packing: 3/15 kg.',
    coverageRate: 0.56,
    wastagePercentage: 10,
    productImage: '/images/ConcreedCreed2K.png',
    _createdDate: new Date('2026-01-15'),
    _updatedDate: new Date('2026-01-15'),
  },
  {
    _id: '2',
    productName: 'CREED PU',
    category: 'Waterproofing Solutions',
    description: 'Single-component polyurethane waterproofing membrane with excellent elasticity and durability.',
    specifications: 'pH: 7-9. Specific Gravity: 1.02-1.03. Coverage: ~20 sq.ft./kg per coat. Packing: 20 kg.',
    coverageRate: 1.86,
    wastagePercentage: 8,
    productImage: '/images/common.png',
    _createdDate: new Date('2026-01-15'),
    _updatedDate: new Date('2026-01-15'),
  },
  {
    _id: '3',
    productName: 'CREED FLEX',
    category: 'Waterproofing Solutions',
    description: 'Flexible cementitious coating with very high elongation for moving substrates.',
    specifications: 'Elasticity: 100-150%. Density: 1.45-1.52 g/cm³. Usage: 0.2-0.3 kg/sq-m (2 coats). Packing: 5/20 kg.',
    coverageRate: 4,
    wastagePercentage: 5,
    productImage: '/images/creedflex.jpeg',
    _createdDate: new Date('2026-01-15'),
    _updatedDate: new Date('2026-01-15'),
  },
  {
    _id: '4',
    productName: 'CREED+',
    category: 'Admixtures',
    description: 'Integral waterproofing liquid for cementitious mixes, reducing permeability and improving durability.',
    specifications: 'Specific Gravity: 1.05-1.07. Chloride: Nil. Dosage: 200 ml per 50 kg cement. Packing: 200 ml / 5 kg / 20 kg.',
    coverageRate: 0.01,
    wastagePercentage: 1,
    productImage: '/images/ConcreedCreedPlusAdmixture.png',
    _createdDate: new Date('2026-01-15'),
    _updatedDate: new Date('2026-01-15'),
  },
  {
    _id: '5',
    productName: 'ADDSURE PCE MG',
    category: 'Admixtures',
    description: 'New generation modified PCE-based superplasticizer for high workability and reduced water demand.',
    specifications: 'Density: 1.1-1.2 g/cm³. pH: 6-7. Dosage: 0.5% to 1.5% by weight of cement. Packing: 210 L drum.',
    coverageRate: 0.005,
    wastagePercentage: 1,
    productImage: '/images/common.png',
    _createdDate: new Date('2026-01-15'),
    _updatedDate: new Date('2026-01-15'),
  },
  {
    _id: '6',
    productName: 'ADDSURE PCE HG',
    category: 'Admixtures',
    description: 'High-performance PCE-based superplasticizer for demanding concrete mixes with superior slump retention.',
    specifications: 'Density: 1.1-1.2 g/cm³. pH: 6-7. Dosage: 0.5% to 1.5% by weight of cement. Packing: 210 L drum.',
    coverageRate: 0.005,
    wastagePercentage: 1,
    productImage: '/images/common.png',
    _createdDate: new Date('2026-01-15'),
    _updatedDate: new Date('2026-01-15'),
  },
  {
    _id: '7',
    productName: 'CREED Crack Filler',
    category: 'Concrete Repair Solutions',
    description: 'Ready-to-use elastomeric crack filler paste for hairline and structural cracks.',
    specifications: 'Ready to use elastomeric paste. Coverage: ~45 RFt/kg for 5mm cracks. Packing: 1 / 5 kg.',
    coverageRate: 45,
    wastagePercentage: 5,
    productImage: '/images/creedcrackfiller.png',
    _createdDate: new Date('2026-01-15'),
    _updatedDate: new Date('2026-01-15'),
  },
  {
    _id: '8',
    productName: 'CREED GPOXY',
    category: 'Concrete Repair Solutions',
    description: 'Three-part epoxy tile grout available in attractive colours for joints 3-10mm.',
    specifications: '3-part epoxy grout. Coverage: ~30 RFt/kg for 3-10mm joint. Packing: 1 / 5 kg.',
    coverageRate: 30,
    wastagePercentage: 8,
    productImage: '/images/creedgpoxy.png',
    _createdDate: new Date('2026-01-15'),
    _updatedDate: new Date('2026-01-15'),
  },
  {
    _id: '9',
    productName: 'CREED LATEX',
    category: 'Concrete Repair Solutions',
    description: 'SBR-based polymer for repair and bonding, improves adhesion and flexibility of repair mortars.',
    specifications: 'SBR polymer. Coverage: 50-55 sq.ft per L (single coat). Packing: 1 / 5 L.',
    coverageRate: 52,
    wastagePercentage: 5,
    productImage: '/images/common.png',
    _createdDate: new Date('2026-01-15'),
    _updatedDate: new Date('2026-01-15'),
  },
  {
    _id: '10',
    productName: 'ZINCREED',
    category: 'Concrete Repair Solutions',
    description: 'Polymer-based anti-corrosive zinc-rich coating for steel reinforcement protection.',
    specifications: 'Polymer anti-corrosive zinc-rich coating. Coverage: 40-50 sq.ft per L. Packing: 5 L.',
    coverageRate: 45,
    wastagePercentage: 5,
    productImage: '/images/zincreed.jpeg',
    _createdDate: new Date('2026-01-15'),
    _updatedDate: new Date('2026-01-15'),
  },
  {
    _id: '11',
    productName: 'MCRETE-PL',
    category: 'Mortar',
    description: 'Fiber-reinforced polymer-modified mortar for thicknesses 9-14mm per coat.',
    specifications: 'Thickness: 9-14mm per coat. Coverage: ~16-20 sq.ft per 40kg. Packing: 40 kg.',
    coverageRate: 18,
    wastagePercentage: 10,
    productImage: '/images/mcretepl.png',
    _createdDate: new Date('2026-01-15'),
    _updatedDate: new Date('2026-01-15'),
  },
  {
    _id: '12',
    productName: 'MCRETE-FIX',
    category: 'Mortar',
    description: 'Ready-mix mortar for AAC block joints; pot life ~2 hours; ideal for thin joints (3mm).',
    specifications: 'Ready mix mortar for AAC block joints. Pot Life: 2 hrs. Coverage: ~90-100 sq.ft per 40kg (3mm). Packing: 25 / 40 kg.',
    coverageRate: 9.5,
    wastagePercentage: 8,
    productImage: '/images/common.png',
    _createdDate: new Date('2026-01-15'),
    _updatedDate: new Date('2026-01-15'),
  },
  {
    _id: '13',
    productName: 'CREED TA-Grey',
    category: 'Tile & Stone Adhesive and Grouts',
    description: 'High-strength tile adhesive in grey suitable for ceramic and vitrified tiles.',
    specifications: 'Compressive Strength: 14 N/mm². Pot Life: 2 hrs.',
    coverageRate: 0.18,
    wastagePercentage: 8,
    productImage: '/images/creedtagrey.png',
    _createdDate: new Date('2026-01-16'),
    _updatedDate: new Date('2026-01-16'),
  },
  {
    _id: '14',
    productName: 'CREED TA GREY+',
    category: 'Tile & Stone Adhesive and Grouts',
    description: 'High-slip resistant grey tile adhesive for heavy-duty tiling applications.',
    specifications: 'Compressive Strength: 12 N/mm². High slip resistance.',
    coverageRate: 0.1625,
    wastagePercentage: 8,
    productImage: '/images/creedtagreyplus.png',
    _createdDate: new Date('2026-01-16'),
    _updatedDate: new Date('2026-01-16'),
  },
  {
    _id: '15',
    productName: 'CREED TA WHITE',
    category: 'Tile & Stone Adhesive and Grouts',
    description: 'Whitish tile adhesive optimized for marble and light-colour stone installations.',
    specifications: 'Whitish color for marble. Compressive Strength: 14 N/mm².',
    coverageRate: 0.175,
    wastagePercentage: 8,
    productImage: '/images/common.png',
    _createdDate: new Date('2026-01-16'),
    _updatedDate: new Date('2026-01-16'),
  },
  {
    _id: '16',
    productName: 'PRIME COAT',
    category: 'Decorative Surface Finish',
    description: 'Primer coating for exterior and interior concrete surfaces to improve adhesion and finish.',
    specifications: 'Primer for exterior and interior concrete surfaces. Coverage: 60-75 sq.ft per L (1 coat). Packing: 20 L.',
    coverageRate: 67,
    wastagePercentage: 5,
    productImage: '/images/primecoat.jpeg',
    _createdDate: new Date('2026-01-16'),
    _updatedDate: new Date('2026-01-16'),
  },
  {
    _id: '17',
    productName: 'CREED TEXTURE',
    category: 'Decorative Surface Finish',
    description: 'Polymer-modified textured coating for external substrates, providing a decorative and durable finish.',
    specifications: 'Polymer Modified Textured Coating. Coverage: ~80-85 sq.ft per 30kg at 1.5mm thickness. Packing: 30 kg.',
    coverageRate: 82.5,
    wastagePercentage: 10,
    productImage: '/images/common.png',
    _createdDate: new Date('2026-01-16'),
    _updatedDate: new Date('2026-01-16'),
  },
  {
    _id: '18',
    productName: 'CREED EMULSION',
    category: 'Decorative Surface Finish',
    description: 'Acrylic emulsion coating offering excellent finish for interior applications with good hide and durability.',
    specifications: 'Acrylic emulsion. Coverage: ~80 sq.ft per L (2 coats). Packing: 20 Kg.',
    coverageRate: 80,
    wastagePercentage: 8,
    productImage: '/images/common.png',
    _createdDate: new Date('2026-01-16'),
    _updatedDate: new Date('2026-01-16'),
  },
  {
    _id: '19',
    productName: 'CREED FHARD',
    category: 'Stamping Solutions',
    description: 'Coloured floor hardener specifically formulated for stamp floor applications to increase wear resistance.',
    specifications: 'Coloured floor hardener for stamp floor. Application rate: 2.6 Kg/sq.m.',
    coverageRate: 2.6,
    wastagePercentage: 5,
    productImage: '/images/common.png',
    _createdDate: new Date('2026-01-16'),
    _updatedDate: new Date('2026-01-16'),
  },
  {
    _id: '20',
    productName: 'CREED FRELEASE',
    category: 'Stamping Solutions',
    description: 'Release powder for stamp floor—prevents stamping tools from sticking and imparts texture/colour separation.',
    specifications: 'Release powder for stamp floor. Coverage: ~600-650 sq.ft per bag.',
    coverageRate: 625,
    wastagePercentage: 3,
    productImage: '/images/common.png',
    _createdDate: new Date('2026-01-16'),
    _updatedDate: new Date('2026-01-16'),
  },
  {
    _id: '21',
    productName: 'CREED SEALER',
    category: 'Stamping Solutions',
    description: 'Transparent polymer sealer for stamp flooring to protect and enhance appearance.',
    specifications: 'Transparent polymer coating. Coverage: ~80 sq.ft per L per coat. Recommended 1–2 coats.',
    coverageRate: 80,
    wastagePercentage: 5,
    productImage: '/images/common.png',
    _createdDate: new Date('2026-01-16'),
    _updatedDate: new Date('2026-01-16'),
  },
];

export const mockTeamMembers: TeamMembers[] = [
  {
    _id: '1',
    name: 'Himanshu Singh',
    role: 'Chief Executive Officer',
    bio: 'An ICT Mumbai Post graduate, is a dedicated Green Tech entrepreneur. His diverse experience in the Chemical and Biotechnology sectors, honed through various roles and his own ventures established in 2022, is invaluable.',
    photo: '/images/himanshusingh.png',
    linkedInProfile: 'https://www.linkedin.com/in/himanshu-singh100/',
    _createdDate: new Date('2026-01-09'),
    _updatedDate: new Date('2026-01-10'),
  },
  {
    _id: '2',
    name: 'AKASH DHIMAN',
    role: 'Head of Sales & Marketing',
    bio: "A dynamic professional with a strong academic background from John Moores University, Liverpool, brings 4 years of experience in the automotive industry. Currently the Marketing Head at Eccofragg Solutions. His B.Tech in Mechanical Engineering from Dr. A.P.J Abdul Kalam Technical University further strengthens his profile. Akash's blend of qualifications and experience makes him an asset to any organization aiming to optimize processes and drive quality initiatives.",
    photo: '/images/akashdhiman.png',
    linkedInProfile: 'https://www.linkedin.com/in/akash-dhimann/',
    _createdDate: new Date('2026-01-11'),
    _updatedDate: new Date('2026-01-12'),
  },
  {
    _id: '3',
    name: 'SARTHAK CHAUHAN',
    role: 'Director of Research & Development',
    bio: "An Automobile Engineering degree, he began a journey on the tracks of progress. As a Production Engineer, he enhanced efficiency an earned team's trust. attention to detail led him to a Quality Engineer role, where his innovative protocols reduced defect rates by 20%. Now, as a Senior Leader, he champion in harmonize production and quality, ensuring optimal performance.",
    photo: '/images/sarthakchauhan.png',
    linkedInProfile: 'https://www.linkedin.com/in/sarthak-chauhan20/',
    _createdDate: new Date('2026-01-11'),
    _updatedDate: new Date('2026-01-12'),
  },
  {
    _id: '4',
    name: 'PALASH SINGH',
    role: 'Chief Operations Officer',
    bio: "A motivated Civil Engineer with a Master's in Environmental Engineering. has diverse experience in Construction Management. Quality Assurance, and Engineering. His analytical approach results in innovative solutions. His attention to detail ensures high-quality project delivery. His Master's from Newcastle University. UK, and involvement in the Jal Jeevan Mission project further enhance his excellence in project execution skills.",
    photo: '/images/palashsingh.png',
    linkedInProfile: 'https://www.linkedin.com/in/palash-singh/',
    _createdDate: new Date('2026-01-11'),
    _updatedDate: new Date('2026-01-12'),
  },
];
