
import { BlogPosts, CalculatorFormulas, ContactInquiries, FAQs, Products, TeamMembers } from './index';


export const mockCalculatorFormulas: CalculatorFormulas[] = [
  {
    _id: '1',
    formulaName: 'Tile Adhesive Standard Coverage',
    description: 'Calculates the total amount of tile adhesive required for a given area, considering the product\'s coverage rate and an optional wastage percentage.',
    calculationLogic: 'area_sqm * coverageRate_kg_per_sqm * (1 + wastage_percentage / 100)',
    variables: 'area_sqm, coverageRate_kg_per_sqm, wastage_percentage',
    outputUnit: 'kg',
    isActive: true,
    lastUpdated: '2026-01-05',
    _createdDate: new Date('2026-01-05'),
    _updatedDate: new Date('2026-01-06'),
  },
  {
    _id: '2',
    formulaName: 'Tile Grout Calculation',
    description: 'Estimates the quantity of grout needed based on the total area, average joint width, joint depth, and product-specific coverage factor.',
    calculationLogic: 'area_sqm * (jointWidth_mm / 1000) * (jointDepth_mm / 1000) * groutFactor_kg_per_cubic_meter * (1 + wastage_percentage / 100)',
    variables: 'area_sqm, jointWidth_mm, jointDepth_mm, groutFactor_kg_per_cubic_meter, wastage_percentage',
    outputUnit: 'kg',
    isActive: true,
    lastUpdated: '2026-01-05',
    _createdDate: new Date('2026-01-05'),
    _updatedDate: new Date('2026-01-06'),
  },
  {
    _id: '3',
    formulaName: 'Liquid Waterproofing Membrane Coverage',
    description: 'Determines the total liters of liquid waterproofing membrane required for a specified area and number of coats, based on the product\'s per-coat coverage rate.',
    calculationLogic: 'area_sqm * numberOfCoats * coverageRate_liters_per_sqm_per_coat * (1 + wastage_percentage / 100)',
    variables: 'area_sqm, numberOfCoats, coverageRate_liters_per_sqm_per_coat, wastage_percentage',
    outputUnit: 'liters',
    isActive: true,
    lastUpdated: '2026-01-05',
    _createdDate: new Date('2026-01-05'),
    _updatedDate: new Date('2026-01-06'),
  },
  {
    _id: '4',
    formulaName: 'Concrete Repair Mortar Volume',
    description: 'Calculates the total volume of concrete repair mortar needed for a specific repair area and average depth, then converts it to kilograms using product density.',
    calculationLogic: 'area_sqm * (averageDepth_mm / 1000) * density_kg_per_cubic_meter * (1 + wastage_percentage / 100)',
    variables: 'area_sqm, averageDepth_mm, density_kg_per_cubic_meter, wastage_percentage',
    outputUnit: 'kg',
    isActive: true,
    lastUpdated: '2026-01-05',
    _createdDate: new Date('2026-01-05'),
    _updatedDate: new Date('2026-01-06'),
  },
  {
    _id: '5',
    formulaName: 'Self-Leveling Compound Coverage',
    description: 'Estimates the quantity of self-leveling compound required for a given area and desired thickness, considering the product\'s density and an optional wastage.',
    calculationLogic: 'area_sqm * (desiredThickness_mm / 1000) * density_kg_per_cubic_meter * (1 + wastage_percentage / 100)',
    variables: 'area_sqm, desiredThickness_mm, density_kg_per_cubic_meter, wastage_percentage',
    outputUnit: 'kg',
    isActive: true,
    lastUpdated: '2026-01-05',
    _createdDate: new Date('2026-01-05'),
    _updatedDate: new Date('2026-01-06'),
  },
];

export const mockContactInquiries: ContactInquiries[] = [
  {
    _id: '1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '+1-555-123-4567',
    message: 'I am interested in your waterproofing solutions for a commercial project. Could you please send me more information on your product range and pricing?',
    submissionDate: '2026-01-15',
    _createdDate: new Date('2026-01-15'),
    _updatedDate: new Date('2026-01-15'),
  },
  {
    _id: '2',
    name: 'Jane Smith',
    email: 'jane.smith@constructionco.com',
    phone: '+1-555-987-6543',
    message: 'I used your adhesive coverage calculator and have a question about the wastage percentage. Does it account for irregular surfaces? We are planning a large tile installation.',
    submissionDate: '2026-01-15',
    _createdDate: new Date('2026-01-15'),
    _updatedDate: new Date('2026-01-15'),
  },
  {
    _id: '1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '+1-555-123-4567',
    message: 'I am interested in your waterproofing solutions for a commercial project. Could you please send me more information on your product range and pricing?',
    submissionDate: '2026-01-15',
    _createdDate: new Date('2026-01-15'),
    _updatedDate: new Date('2026-01-15'),
  },
];

export const mockFAQs: FAQs[] = [
  {
    _id: '1',
    question: 'How accurate is the material coverage calculator?',
    answer: 'Our material coverage calculator uses product-specific formulas and coverage rates defined by our experts. While it provides highly accurate estimations for planning, actual material usage may vary slightly based on site conditions, application techniques, and waste. We recommend adding a small buffer to your estimates.',
    category: 'Calculator',
    isFeatured: true,
    lastUpdated: '2026-01-12',
    _createdDate: new Date('2026-01-12'),
    _updatedDate: new Date('2026-01-13'),
  },
  {
    _id: '2',
    question: 'What types of construction materials do you offer?',
    answer: 'We offer a comprehensive range of construction materials including waterproofing solutions, tile & stone adhesives and grouts, concrete repair solutions, flooring systems, stamping solutions, decorative surface finishes, texture paint coatings, admixtures, and mortars.',
    category: 'Products',
    isFeatured: true,
    lastUpdated: '2026-01-12',
    _createdDate: new Date('2026-01-12'),
    _updatedDate: new Date('2026-01-13'),
  },
  {
    _id: '3',
    question: 'How do I use the material coverage calculator?',
    answer: 'Simply navigate to the \'Calculator\' section. You can input the length and width of your area or directly enter the total square meters. Then, select the product you intend to use. The calculator will automatically apply the product\'s specific coverage rate and any optional wastage percentage to provide an estimated material quantity.',
    category: 'Calculator',
    isFeatured: true,
    lastUpdated: '2026-01-12',
    _createdDate: new Date('2026-01-12'),
    _updatedDate: new Date('2026-01-13'),
  },
  {
    _id: '4',
    question: 'Can I get technical support for product application?',
    answer: 'Yes, our technical support team is available to assist you with product selection, application guidelines, and troubleshooting. Please contact us via phone or email, or fill out the contact form on our website, and a specialist will get back to you promptly.',
    category: 'Application',
    isFeatured: true,
    lastUpdated: '2026-01-12',
    _createdDate: new Date('2026-01-12'),
    _updatedDate: new Date('2026-01-13'),
  },
  {
    _id: '5',
    question: 'What is the typical delivery time for orders?',
    answer: 'Delivery times vary based on product availability, order size, and your location. Standard deliveries typically take 3-5 business days. For urgent orders or specific delivery inquiries, please contact our sales team directly.',
    category: 'Ordering & Delivery',
    isFeatured: true,
    lastUpdated: '2026-01-12',
    _createdDate: new Date('2026-01-12'),
    _updatedDate: new Date('2026-01-13'),
  },
  {
    _id: '6',
    question: 'Are your products environmentally friendly?',
    answer: 'We are committed to sustainability and offer a range of eco-friendly products designed to minimize environmental impact. Look for specific product certifications and details on our product pages or contact us for more information on our green building solutions.',
    category: 'Products',
    isFeatured: true,
    lastUpdated: '2026-01-12',
    _createdDate: new Date('2026-01-12'),
    _updatedDate: new Date('2026-01-13'),
  },
  {
    _id: '7',
    question: 'How do I find the right product for my project?',
    answer: 'Our website features a detailed product catalog with descriptions, technical data sheets, and application guides. You can browse by category or use the search function. If you need personalized assistance, our experts are happy to provide recommendations based on your project requirements.',
    category: 'Products',
    isFeatured: true,
    lastUpdated: '2026-01-12',
    _createdDate: new Date('2026-01-12'),
    _updatedDate: new Date('2026-01-13'),
  },
  {
    _id: '8',
    question: 'Is the website accessible on mobile devices?',
    answer: 'Yes, our website is fully responsive and optimized for mobile, tablet, and desktop devices. You can access all features, including the material calculator and product catalog, seamlessly from any device. It\'s also a Progressive Web App (PWA) for an enhanced mobile experience.',
    category: 'Website',
    isFeatured: true,
    lastUpdated: '2026-01-12',
    _createdDate: new Date('2026-01-12'),
    _updatedDate: new Date('2026-01-13'),
  },
  {
    _id: '9',
    question: 'What is the difference between tile adhesive and grout?',
    answer: 'Tile adhesive is used to bond tiles to a substrate, providing a strong and durable connection. Grout, on the other hand, is used to fill the spaces between tiles after they have been laid, providing structural integrity, preventing dirt accumulation, and enhancing the aesthetic appeal.',
    category: 'Products',
    isFeatured: true,
    lastUpdated: '2026-01-12',
    _createdDate: new Date('2026-01-12'),
    _updatedDate: new Date('2026-01-13'),
  },
  {
    _id: '10',
    question: 'How can I get a quote for a large project?',
    answer: 'For large-scale projects or bulk orders, please contact our sales department directly through the \'Contact Us\' page. Provide details about your project, including product requirements and quantities, and our team will prepare a customized quote for you.',
    category: 'Ordering & Delivery',
    isFeatured: true,
    lastUpdated: '2026-01-12',
    _createdDate: new Date('2026-01-12'),
    _updatedDate: new Date('2026-01-13'),
  },
];

export const mockProducts: Products[] = [
  {
    _id: '1',
    productName: 'FlexiSeal Pro Waterproofing',
    category: 'Waterproofing Solutions',
    description: 'A two-component, polymer-modified cementitious waterproofing membrane for concrete and masonry surfaces. Ideal for bathrooms, balconies, and swimming pools.',
    specifications: 'ASTM C1202, EN 14891. Pot life: 60 mins. Curing time: 7 days. Application temperature: 5°C to 35°C.',
    coverageRate: 1.5,
    wastagePercentage: 10,
    productImage: '/images/FlexiSealProWaterproofing.png',
    _createdDate: new Date('2026-01-03'),
    _updatedDate: new Date('2026-01-04'),
  },
  {
    _id: '2',
    productName: 'AquaGuard PU Membrane',
    category: 'Waterproofing Solutions',
    description: 'A single-component, liquid-applied polyurethane waterproofing membrane for roofs, terraces, and wet areas. Forms a seamless, elastic, and durable barrier.',
    specifications: 'ASTM C836, ETAG 005. Elongation: >600%. Tensile strength: 3 MPa. Tack-free time: 6 hours.',
    coverageRate: 1.2,
    wastagePercentage: 8,
    productImage: '/images/AquaGuardPUMembrane.png',
    _createdDate: new Date('2026-01-07'),
    _updatedDate: new Date('2026-01-08'),
  },
  {
    _id: '3',
    productName: 'TileMaster Pro Adhesive',
    category: 'Tile & Stone Adhesive and Grouts',
    description: 'A high-performance, polymer-modified cementitious adhesive for fixing all types of tiles and natural stone on various substrates. Suitable for internal and external applications.',
    specifications: 'EN 12004 C2TE S1. Open time: 30 mins. Pot life: 4 hours. Slip resistance: <0.5mm.',
    coverageRate: 4,
    wastagePercentage: 5,
    productImage: '/images/TileMasterProAdhesive.png',
    _createdDate: new Date('2026-01-07'),
    _updatedDate: new Date('2026-01-08'),
  },
  {
    _id: '4',
    productName: 'DuraGrout Epoxy',
    category: 'Tile & Stone Adhesive and Grout',
    description: 'A two-component, acid-resistant epoxy grout for ceramic tiles, vitrified tiles, and natural stone. Ideal for areas requiring high hygiene and chemical resistance.',
    specifications: 'EN 13888 RG. Pot life: 45 mins. Walkable after: 24 hours. Chemical resistance: Excellent.',
    coverageRate: 0.8,
    wastagePercentage: 15,
    productImage: '/images/DuraGroutEpoxy.png',
    _createdDate: new Date('2026-01-07'),
    _updatedDate: new Date('2026-01-08'),
  },
  {
    _id: '5',
    productName: 'SpeedFix Tile Adhesive',
    category: 'Tile & Stone Adhesive and Grout',
    description: 'A rapid-setting, polymer-modified cementitious adhesive for quick tile installations. Allows for grouting in just 3 hours.',
    specifications: 'EN 12004 C2F. Open time: 15 mins. Pot life: 30 mins. Grout after: 3 hours.',
    coverageRate: 1.2,
    wastagePercentage: 8,
    productImage: '/images/SpeedFixTileAdhesive.png',
    _createdDate: new Date('2026-01-07'),
    _updatedDate: new Date('2026-01-08'),
  },
  {
    _id: '6',
    productName: 'ReCon Structural Mortar',
    category: 'Concrete Repair Solutions',
    description: 'A high-strength, polymer-modified, fiber-reinforced repair mortar for structural concrete repairs. Excellent bond to existing concrete.',
    specifications: 'EN 1504-3 R3. Compressive strength: >40 MPa. Layer thickness: 10-50mm.',
    coverageRate: 2,
    wastagePercentage: 10,
    productImage: '/images/ReConStructuralMortar.png',
    _createdDate: new Date('2026-01-07'),
    _updatedDate: new Date('2026-01-08'),
  },
  {
    _id: '7',
    productName: 'CrackSeal Epoxy Filler',
    category: 'Concrete Repair Solutions',
    description: 'A two-component, low-viscosity epoxy resin for injecting and filling cracks in concrete structures. Restores structural integrity.',
    specifications: 'ASTM C881 Type I, II, IV, V, Grade 1. Viscosity: 200-400 cps. Pot life: 20 mins.',
    coverageRate: 1,
    wastagePercentage: 20,
    productImage: '/images/CrackSealEpoxyFiller.png',
    _createdDate: new Date('2026-01-07'),
    _updatedDate: new Date('2026-01-08'),
  },
  {
    _id: '8',
    productName: 'LevelFloor SLU',
    category: 'Flooring Solutions',
    description: 'A cementitious, self-leveling underlayment for smoothing and leveling interior concrete substrates before installing floor coverings.',
    specifications: 'ASTM C1708. Compressive strength: >25 MPa. Walkable after: 4 hours. Layer thickness: 3-15mm.',
    coverageRate: 1.7,
    wastagePercentage: 5,
    productImage: '/images/LevelFloorSLU.png',
    _createdDate: new Date('2026-01-07'),
    _updatedDate: new Date('2026-01-08'),
  },
  {
    _id: '9',
    productName: 'DuraCoat Industrial Epoxy',
    category: 'Flooring Solutions',
    description: 'A two-component, solvent-free epoxy coating for industrial floors requiring high abrasion and chemical resistance.',
    specifications: 'ASTM D4060, ASTM D2240. Abrasion resistance: Excellent. Chemical resistance: High. Pot life: 30 mins.',
    coverageRate: 0.25,
    wastagePercentage: 8,
    productImage: '/images/DuraCoatIndustrialEpoxy.png',
    _createdDate: new Date('2026-01-07'),
    _updatedDate: new Date('2026-01-08'),
  },
  {
    _id: '10',
    productName: 'FormEase Release Agent',
    category: 'Stamping Solutions',
    description: 'A liquid release agent for stamped concrete applications, preventing stamping tools from sticking to fresh concrete.',
    specifications: 'Non-staining, VOC compliant. Application: Spray or brush.',
    coverageRate: 0.1,
    wastagePercentage: 10,
    productImage: '/images/FormEaseReleaseAgent.png',
    _createdDate: new Date('2026-01-07'),
    _updatedDate: new Date('2026-01-08'),
  },
  {
    _id: '11',
    productName: 'StampGuard Sealer',
    category: 'Stamping Solutions',
    description: 'An acrylic-based, clear sealer for stamped concrete, enhancing color and providing protection against abrasion and weathering.',
    specifications: 'UV resistant, non-yellowing. Drying time: 2-4 hours. Recoat time: 4-6 hours.',
    coverageRate: 0.2,
    wastagePercentage: 5,
    productImage: '/images/StampGuardSealer.png',
    _createdDate: new Date('2026-01-07'),
    _updatedDate: new Date('2026-01-08'),
  },
  {
    _id: '12',
    productName: 'DecoMicro Cement',
    category: 'Decorative Surface Finish',
    description: 'A decorative, thin-layer microcement system for creating seamless, modern finishes on floors, walls, and furniture.',
    specifications: 'Adhesion: Excellent. Layer thickness: 2-3mm total. Curing time: 7 days.',
    coverageRate: 1,
    wastagePercentage: 12,
    productImage: '/images/DecoMicroCement.png',
    _createdDate: new Date('2026-01-07'),
    _updatedDate: new Date('2026-01-08'),
  },
  {
    _id: '13',
    productName: 'WallArt Texture Paint',
    category: 'Texture Paint Coatings',
    description: 'A high-quality acrylic texture paint for interior and exterior walls, providing a durable and decorative finish.',
    specifications: 'Weather resistant, alkali resistant. Drying time: 4-6 hours. Application: Trowel or roller.',
    coverageRate: 0.5,
    wastagePercentage: 7,
    productImage: '/images/WallArtTexturePaint.png',
    _createdDate: new Date('2026-01-07'),
    _updatedDate: new Date('2026-01-08'),
  },
  {
    _id: '14',
    productName: 'FlowEnhance Admixture',
    category: 'Admixtures',
    description: 'A high-range water-reducing superplasticizer for concrete, improving workability and strength without increasing water content.',
    specifications: 'ASTM C494 Type F. Dosage: 0.5-2.0% by weight of cement.',
    coverageRate: 0.01,
    wastagePercentage: 3,
    productImage: '/images/FlowEnhanceAdmixture.png',
    _createdDate: new Date('2026-01-07'),
    _updatedDate: new Date('2026-01-08'),
  },
  {
    _id: '15',
    productName: 'BuildStrong Masonry Mortar',
    category: 'Mortar',
    description: 'A pre-mixed, high-strength masonry mortar for brickwork, blockwork, and stone masonry. Provides excellent bond and durability.',
    specifications: 'ASTM C270 Type S. Compressive strength: >12 MPa. Pot life: 2 hours.',
    coverageRate: 20,
    wastagePercentage: 10,
    productImage: '/images/BuildStrongMasonryMortar.png',
    _createdDate: new Date('2026-01-07'),
    _updatedDate: new Date('2026-01-08'),
  },
];

export const mockTeamMembers: TeamMembers[] = [
  {
    _id: '1',
    name: 'Dr. Anya Sharma',
    role: 'Chief Executive Officer',
    bio: 'Dr. Anya Sharma is the visionary leader behind our company, driving innovation and sustainable growth in the construction materials industry. With over 20 years of experience in material science and business development, she is committed to delivering high-quality, eco-friendly solutions.',
    photo: '/images/anyasharma.png',
    linkedInProfile: 'https://linkedin.com/in/anyasharma',
    _createdDate: new Date('2026-01-09'),
    _updatedDate: new Date('2026-01-10'),
  },
  {
    _id: '2',
    name: 'Mark Thompson',
    role: 'Head of Sales & Marketing',
    bio: "Mark Thompson leads our dynamic sales and marketing teams, focusing on expanding our market reach and building strong client relationships. His strategic approach and deep understanding of customer needs have been instrumental in our company's success.",
    photo: '/images/markthompson.png',
    linkedInProfile: 'https://linkedin.com/in/markthompson',
    _createdDate: new Date('2026-01-11'),
    _updatedDate: new Date('2026-01-12'),
  },
  {
    _id: '3',
    name: 'Sarah Chen',
    role: 'Director of Research & Development',
    bio: "Sarah Chen is at the forefront of our product innovation, leading the R&D department in developing cutting-edge construction material solutions. Her expertise in chemical engineering ensures our products meet the highest standards of performance and durability.",
    photo: '/images/sarahchen.png',
    linkedInProfile: 'https://linkedin.com/in/sarahchen',
    _createdDate: new Date('2026-01-11'),
    _updatedDate: new Date('2026-01-12'),
  },
  {
    _id: '4',
    name: 'David Miller',
    role: 'Chief Operations Officer',
    bio: "David Miller oversees all operational aspects, from manufacturing to supply chain management, ensuring efficiency and quality across our production processes. His meticulous planning guarantees timely delivery and consistent product availability.",
    photo: '/images/davidmiller.png',
    linkedInProfile: 'https://linkedin.com/in/davidmiller',
    _createdDate: new Date('2026-01-11'),
    _updatedDate: new Date('2026-01-12'),
  },
  {
    _id: '5',
    name: 'Emily White',
    role: 'Senior Product Manager',
    bio: "Emily White is responsible for the lifecycle of our key product lines, ensuring they align with market demands and customer expectations. Her analytical skills and product development experience are crucial for our portfolio's success.",
    photo: '/images/emilywhite.png',
    linkedInProfile: 'https://linkedin.com/in/emilywhite',
    _createdDate: new Date('2026-01-11'),
    _updatedDate: new Date('2026-01-12'),
  },
  {
    _id: '6',
    name: 'Michael Brown',
    role: 'Technical Support Lead',
    bio: "Michael Brown leads our technical support team, providing expert guidance and solutions to our clients regarding product application and performance. His extensive field experience ensures practical and effective support for all projects.",
    photo: '/images/michaelbrown.png',
    linkedInProfile: 'https://linkedin.com/in/michaelbrown',
    _createdDate: new Date('2026-01-11'),
    _updatedDate: new Date('2026-01-12'),
  },
];
